# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-13 04:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentSlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10)),
                ('startTime', models.CharField(max_length=20)),
                ('endTime', models.CharField(max_length=20)),
                ('isBooked', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('startDate', models.CharField(max_length=10)),
                ('startTime', models.CharField(max_length=20)),
                ('endTime', models.CharField(max_length=10)),
                ('DateList', models.TextField(null=True)),
                ('rangeStartDate', models.CharField(max_length=10, null=True)),
                ('rangeEndDate', models.CharField(max_length=10, null=True)),
                ('whenToNotify', models.IntegerField(null=True)),
                ('notificationPref', models.CharField(max_length=20, null=True)),
                ('location', models.CharField(max_length=100, null=True)),
                ('isAppointment', models.BooleanField()),
                ('apptSlot', models.IntegerField(null=True)),
                ('apptCalendarUrl', models.CharField(max_length=100, null=True)),
                ('token', models.CharField(max_length=10)),
                ('admins', models.ManyToManyField(related_name='admins', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserWithFields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events', models.ManyToManyField(to='projectcalendar.Event')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcalendar.Event'),
        ),
        migrations.AddField(
            model_name='appointmentslot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
