# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 00:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
