# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projectcalendar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='DateList',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rangeEndDate',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rangeStartDate',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
