# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 00:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projectcalendar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EM_Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_token', models.CharField(max_length=100)),
                ('em_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projectcalendar.Event')),
                ('em_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitee', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='em_token',
            unique_together=set([('em_event', 'em_user')]),
        ),
    ]
